# Generated by Django 3.2.4 on 2021-09-15 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='The year level appropriate for the OSCE station', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(help_text='A speciality for the Station/MCQ OSCEStation e.g. Cardiology', max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.CharField(help_text='The type of OSCE station, e.g. Examination', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OSCEStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the OSCE station', max_length=128, unique=True)),
                ('stem', martor.models.MartorField(help_text='OSCE Stem to be shown to the candidate completing the station')),
                ('patient_script', martor.models.MartorField(help_text='Patient script for the person acting as patient')),
                ('marking_guide', martor.models.MartorField(help_text='Marking guide for the station')),
                ('supporting_notes', martor.models.MartorField(help_text='Supporting notes for the station')),
                ('is_flagged', models.BooleanField(default=False, help_text='If True, has been flagged by a user')),
                ('is_reviewed', models.BooleanField(default=False, help_text='If True, has been reviewed by a staff or admin')),
                ('stem_image', models.ImageField(blank=True, help_text='Upload an image to be shown in the OSCE station stem', null=True, upload_to='', verbose_name='Stem image')),
                ('marking_guide_image', models.ImageField(blank=True, help_text='Upload an image to be shown with the marking guide', null=True, upload_to='', verbose_name='Marking Guide image')),
                ('supporting_notes_image', models.ImageField(blank=True, help_text='Upload an image to be shown alongside the supporting notes', null=True, upload_to='', verbose_name='Further Notes image')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flagged_osce_stations', to=settings.AUTH_USER_MODEL)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='osce_bank.level')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_osce_stations', to=settings.AUTH_USER_MODEL)),
                ('specialities', models.ManyToManyField(to='osce_bank.Speciality')),
                ('types', models.ManyToManyField(to='osce_bank.StationType')),
            ],
            options={
                'verbose_name': 'OSCE Station',
                'verbose_name_plural': 'OSCE Stations',
            },
        ),
        migrations.CreateModel(
            name='OSCEHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_stations', models.ManyToManyField(related_name='osce_user_histories', to='osce_bank.OSCEStation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='osce_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'OSCE User History',
                'verbose_name_plural': 'OSCE User Histories',
            },
        ),
    ]
