# Generated by Django 3.2.10 on 2022-01-01 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osce_bank', '0001_squashed_0004_alter_oscestation_flagged_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscestation',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the OSCE Station was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oscestation',
            name='review_date',
            field=models.DateField(blank=True, help_text='Date the OSCE station was reviewed', null=True),
        ),
    ]
