# Generated by Django 3.2.4 on 2021-09-26 09:18

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('osce_bank', '0002_auto_20210924_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscestation',
            name='flagged_message',
            field=models.TextField(blank=True, help_text='Explanation for why question was flagged.', null=True),
        ),
        migrations.AlterField(
            model_name='oscestation',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='If True, has been flagged by a user and is awaiting review'),
        ),
        migrations.AlterField(
            model_name='oscestation',
            name='marking_guide',
            field=martor.models.MartorField(blank=True, help_text='Marking guide for the station', null=True),
        ),
        migrations.AlterField(
            model_name='oscestation',
            name='supporting_notes',
            field=martor.models.MartorField(blank=True, help_text='Supporting notes for the station', null=True),
        ),
    ]
