# Generated by Django 3.2.4 on 2021-09-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osce_bank', '0003_auto_20210926_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscestation',
            name='flagged_message',
            field=models.TextField(blank=True, help_text='Explanation for why the station was flagged.', null=True),
        ),
    ]
