# Generated by Django 3.2.10 on 2021-12-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('frontend', '0001_initial'), ('frontend', '0002_supporter'), ('frontend', '0003_alter_supporter_image'), ('frontend', '0004_officialdocumentation'), ('frontend', '0005_alter_officialdocumentation_options'), ('frontend', '0006_officialdocumentation_publish_year'), ('frontend', '0007_publication'), ('frontend', '0008_conferencereport'), ('frontend', '0009_auto_20210822_1849'), ('frontend', '0010_auto_20210822_1900')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sponsor', max_length=128, unique=True)),
                ('website', models.CharField(help_text="URL of the sponsor's website", max_length=256)),
                ('image', models.ImageField(help_text='Supporter image for display on frontend', upload_to='frontend/sponsors')),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the supporter', max_length=128, unique=True)),
                ('website', models.CharField(help_text="URL of the supporter's website", max_length=256)),
                ('image', models.ImageField(help_text='Supporter image for display on frontend', null=True, upload_to='frontend/sponsors')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the document', max_length=256, unique=True)),
                ('file', models.FileField(upload_to='official_documentation')),
                ('publish_year', models.IntegerField(default=1990)),
            ],
            options={
                'verbose_name': 'Official Documentation',
                'verbose_name_plural': 'Official Documentation',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the publication', max_length=256)),
                ('pdf', models.FileField(upload_to='publications')),
                ('pub_date', models.DateField(help_text='Publication date, generally the 1st of a month')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='publication_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(help_text='Name of the conference', max_length=256)),
                ('conference_year', models.IntegerField(help_text='Year of the conference, e.g 2018')),
                ('conference_city', models.CharField(help_text="City (and country if not obvious) where the elective took place, e.g. 'Canberra' or 'Vienna, Austria'", max_length=128)),
                ('report_author', models.CharField(help_text='Name of the author of the report', max_length=256)),
                ('file', models.FileField(upload_to='tcss_reports')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_name', models.CharField(help_text='Name of the elective', max_length=256)),
                ('elective_year', models.IntegerField(help_text='Year of the elective, e.g 2018')),
                ('elective_city', models.CharField(help_text="City (and country if not obvious) where the elective took place, e.g. 'Canberra' or 'Vienna, Austria'", max_length=128)),
                ('report_author', models.CharField(help_text='Name of the author of the report', max_length=256)),
                ('file', models.FileField(upload_to='tcss_reports')),
            ],
        ),
    ]
