# Generated by Django 3.2.4 on 2021-07-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the supporter', max_length=128, unique=True)),
                ('website', models.CharField(help_text="URL of the supporter's website", max_length=256)),
                ('image', models.ImageField(help_text='Supporter image for display on frontend', null=True, upload_to='frontend/supporters')),
            ],
        ),
    ]
