# Generated by Django 3.2.10 on 2022-01-21 02:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_officialdocumentation_publish_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text="Type of publication, e.g. 'The Pulse' or 'Student Survival Guide'", max_length=256)),
                ('machine_type', models.CharField(blank=True, help_text='Machine readable type, autogenerated from type', max_length=256, null=True)),
                ('display_description', tinymce.models.HTMLField(default='', help_text='The description to show on the publications page above the publications')),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='A thumbnail for the publicattion to be shown on the website. Will be auto-generated when the pdf is saved to the new object.', null=True, upload_to='publication_thumbnails'),
        ),
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='frontend.publicationtype'),
        ),
    ]
