# Generated by Django 3.2.4 on 2021-08-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_supporter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the document', max_length=256, unique=True)),
                ('file', models.FileField(upload_to='official_documentation')),
            ],
        ),
    ]
