# Generated by Django 3.2.4 on 2021-08-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_officialdocumentation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialdocumentation',
            options={'verbose_name': 'Official Documentation', 'verbose_name_plural': 'Official Documentation'},
        ),
    ]
