# Generated by Django 3.2.4 on 2021-08-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_officialdocumentation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocumentation',
            name='publish_year',
            field=models.IntegerField(default=1990),
            preserve_default=False,
        ),
    ]
