# Generated by Django 3.2.10 on 2022-01-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_publicationtype_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='frontend.publicationtype'),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='machine_type',
            field=models.CharField(help_text='Machine readable type, autogenerated from type', max_length=256, null=True),
        ),
    ]
