# Generated by Django 3.2.4 on 2021-08-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_officialdocumentation_publish_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the publication', max_length=256)),
                ('pdf', models.FileField(upload_to='publications')),
                ('pub_date', models.DateField(help_text='Publication date, generally the 1st of a month')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='publication_thumbnails')),
            ],
        ),
    ]
