# Generated by Django 3.2.4 on 2021-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(help_text='Name of the conference', max_length=256)),
                ('conference_year', models.IntegerField(help_text='Year of the conference year, e.g 2018')),
                ('conference_city', models.CharField(help_text="City where the conference took place, e.g. 'Canberra'", max_length=128)),
                ('report_author', models.CharField(help_text='Name of the author of the report', max_length=256)),
                ('file', models.FileField(upload_to='tcss_reports')),
            ],
        ),
    ]
