# Generated by Django 3.2.4 on 2021-08-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20210822_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencereport',
            name='conference_city',
            field=models.CharField(help_text="City (and country if not obvious) where the elective took place, e.g. 'Canberra' or 'Vienna, Austria'", max_length=128),
        ),
        migrations.AlterField(
            model_name='electivereport',
            name='elective_city',
            field=models.CharField(help_text="City (and country if not obvious) where the elective took place, e.g. 'Canberra' or 'Vienna, Austria'", max_length=128),
        ),
    ]
