# Generated by Django 3.2.10 on 2021-12-26 06:57

import cuser.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_memberrecordsimport_file'), ('users', '0003_alter_memberrecordsimport_import_dt'), ('users', '0004_alter_memberrecordsimport_members'), ('users', '0005_auto_20210620_1206'), ('users', '0006_alter_memberrecordsimport_members'), ('users', '0007_memberrecordsimport_report_date'), ('users', '0008_alter_memberrecordsimport_report_date'), ('users', '0009_auto_20210928_1006'), ('users', '0010_user_is_medusa')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRecord',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('end_date', models.DateField(verbose_name='End date')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRecordsImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_dt', models.DateTimeField(auto_now_add=True, verbose_name='Import time')),
                ('members', models.ManyToManyField(blank=True, related_name='member_record_imports', to='users.MemberRecord')),
                ('file', models.FileField(blank=True, null=True, upload_to='dusa_reports/%Y')),
                ('report_date', models.DateField(help_text='Date the report was generated', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True, verbose_name='Email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('is_medusa', models.BooleanField(default=False, help_text='Designates whether this user is associated with a medusa.org.au email address.', verbose_name='Is a medusa.org.au user')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', cuser.models.CUserManager()),
            ],
        ),
    ]
