# Generated by Django 3.2.10 on 2022-01-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0010_user_is_medusa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Type of contribution, e.g. 'Organised MCQ Night'", max_length=128, unique=True)),
                ('requires_signoff', models.BooleanField(default=True, help_text='True if this contribution requires signoff by a executive member')),
                ('signoff_requirements', models.TextField(blank=True, help_text='Any sign off requirements for the contribution, e.g. uploading MCQ slides to MeDUSA drive', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionCertificate',
            fields=[
                ('user', models.OneToOneField(help_text='User the this contribution certificate corresponds to. Note there will only be one certificate at any one time', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='contribution_certificate', serialize=False, to='users.user')),
                ('description', models.CharField(help_text='Description of the contribution. E.g. DSIG MCQ Night', max_length=128)),
                ('date_modified', models.DateField(auto_now=True, help_text='Date the certificate was generated')),
                ('signed_off_date', models.DateField(blank=True, help_text='Date the contribution was signed off', null=True)),
                ('signed_off_by', models.ForeignKey(blank=True, help_text='User who signed off contribution, if required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_contribution_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the contribution occurred')),
                ('description', models.CharField(help_text='Description of the contribution. E.g. DSIG MCQ Night. \nFor auto-generated like Question and OSCE Bank creation, this field will be filled the unique ID of the question or OSCE station', max_length=128, unique=True)),
                ('signed_off_date', models.DateField(blank=True, help_text='Date the contribution was signed off', null=True)),
                ('signed_off_by', models.ForeignKey(blank=True, help_text='User who signed off contribution, if required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_contributions', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='users.contributiontype')),
                ('user', models.ForeignKey(help_text='User the this contribution corresponds to', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'type', 'description')},
            },
        ),
    ]
