# Generated by Django 3.2.4 on 2021-06-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_memberrecordsimport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecordsimport',
            name='import_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='import time'),
        ),
    ]
