# Generated by Django 3.2.10 on 2022-01-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contribution_contributioncertificate_contributiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='machine_name',
            field=models.CharField(default='', help_text='Machine readable type of contribution, e.g. MCQ_NIGHT_ORGANISE. Must be unique', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='name',
            field=models.CharField(help_text="Human readable type of contribution, e.g. 'Organised MCQ Night'. Must be unique.", max_length=128, unique=True),
        ),
    ]
