# Generated by Django 3.2.4 on 2021-06-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_memberrecordsimport_import_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecordsimport',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='users.MemberRecord'),
        ),
    ]
