# Generated by Django 3.2.10 on 2022-01-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contribution_is_signed_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='requires_signing',
            field=models.BooleanField(default=True, help_text='If true, it needs signing off by a sign off approver'),
        ),
    ]
