# Generated by Django 3.2.4 on 2021-06-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_memberrecordsimport_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberrecord',
            name='import_records',
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='memberrecordsimport',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_record_imports', to='users.MemberRecord'),
        ),
    ]
