# Generated by Django 3.1.6 on 2021-02-14 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210214_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRecord',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRecordsImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='import time')),
                ('members', models.ManyToManyField(to='users.MemberRecord')),
            ],
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='import_records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.memberrecordsimport'),
        ),
    ]
