# Generated by Django 3.2.10 on 2022-01-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contribution_requires_signing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributioncertificate',
            name='description',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='is_signed_off',
            field=models.BooleanField(default=False, help_text='This will change status after signing off, do not edit this field manually.'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='requires_signing',
            field=models.BooleanField(default=True, help_text='If true, it needs signing off by a sign off approver. This will change status after signing off, do not edit this field manually.'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='signed_off_date',
            field=models.DateField(blank=True, help_text='Date the contribution was signed off. This will be auto filled upon signing, do not edit manually', null=True),
        ),
    ]
