# Generated by Django 3.1.6 on 2021-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210214_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberrecord',
            name='import_records',
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='import_records',
            field=models.ManyToManyField(to='users.MemberRecordsImport'),
        ),
    ]
