# Generated by Django 3.2.4 on 2021-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210620_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecordsimport',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_record_imports', to='users.MemberRecord'),
        ),
    ]
