# Generated by Django 3.2.10 on 2022-01-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220101_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_expiry',
            field=models.DateField(blank=True, help_text='Date their membership expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Image of the users signature, only used for signing certificates', null=True, upload_to='signatures'),
        ),
    ]
