# Generated by Django 3.2.4 on 2021-09-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_memberrecordsimport_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecordsimport',
            name='report_date',
            field=models.DateField(help_text='Date the report was generated', unique=True),
        ),
    ]
