# Generated by Django 3.2.10 on 2022-01-02 23:19

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220102_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributioncertificate',
            name='details',
            field=martor.models.MartorField(blank=True, help_text='Markdown formatted details. This will be generated automatically by user.generate_contribution_certificate, but can be modified afterwards as well.', null=True),
        ),
    ]
