# Generated by Django 3.2.10 on 2022-01-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=True, help_text='Designates whether the user is a member of MeDUSA. Non-members include @medusa.org.au addresses, external clubs with accounts', verbose_name='Is a MeDUSA member'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_id',
            field=models.CharField(blank=True, error_messages={'unique': 'The Member ID of a user must be unique!'}, max_length=12, null=True, unique=True, verbose_name='Member iD'),
        ),
    ]
