# Generated by Django 3.2.7 on 2021-09-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210928_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_medusa',
            field=models.BooleanField(default=False, help_text='Designates whether this user is associated with a medusa.org.au email address.', verbose_name='Is a medusa.org.au user'),
        ),
    ]
