# Generated by Django 3.2.7 on 2021-10-03 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_medusa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrib_type', models.CharField(choices=[('MCQ_NIGHT', 'Mcq Night')], max_length=128)),
                ('title', models.CharField(help_text='Title / name of the contribution', max_length=192)),
                ('completed_date', models.DateField(help_text='Date the contribution was completed. If it was over multiple date, give the last date')),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_contributions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
