# Generated by Django 3.2.10 on 2022-01-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_is_medusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='date_welcome_email_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='is_welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
