# Generated by Django 3.2.7 on 2021-10-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
