# Generated by Django 3.2.10 on 2022-01-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220103_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='import_date',
            field=models.DateField(auto_now=True),
        ),
    ]
