# Generated by Django 3.2.7 on 2021-10-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_contribution_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contrib_type',
            field=models.CharField(choices=[('MCQ', 'MCQ Night')], max_length=128),
        ),
    ]
