# Generated by Django 3.2.9 on 2021-12-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_contribution_contrib_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contrib_type',
            field=models.CharField(choices=[('MCQ', 'MCQ Night')], max_length=128, verbose_name='Contribution type'),
        ),
    ]
