# Generated by Django 3.2.10 on 2022-01-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_memberrecord_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='import_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
