# Generated by Django 3.2.10 on 2022-01-03 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_memberrecord_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributioncertificate',
            name='user',
            field=models.OneToOneField(help_text='User the this contribution certificate corresponds to. Note there will only be one certificate at any one time', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contribution_certificate', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
