# Generated by Django 3.2.10 on 2022-01-03 11:05

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_contributiontype_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributioncertificate',
            name='details',
            field=martor.models.MartorField(blank=True, help_text='Markdown formatted details. This will be generated automatically by ContributionCertificate.gen_cert_detail_text, but can be modified afterwards as well.', null=True),
        ),
    ]
