# Generated by Django 3.2.10 on 2022-01-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_contributioncertificate_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='template',
            field=models.CharField(blank=True, help_text='Template for certificate, use $COUNT to replace with count of that achieviement.', max_length=128, null=True),
        ),
    ]
