# Generated by Django 3.2.10 on 2022-01-03 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_contributiontype_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributioncertificate',
            name='autogenerated',
            field=models.BooleanField(default=False, help_text='If True, was autogenerated by the user'),
        ),
        migrations.AlterField(
            model_name='contributioncertificate',
            name='user',
            field=models.OneToOneField(help_text='User the this contribution certificate corresponds to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contribution_certificates', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='template',
            field=models.CharField(blank=True, help_text="Template for certificate, use $COUNT to replace with count of that contribution. E.g 'Creating $COUNT MCQ Bank Questions'", max_length=128, null=True),
        ),
    ]
