# Generated by Django 3.2.10 on 2022-01-03 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220104_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributioncertificate',
            name='user',
            field=models.ForeignKey(help_text='User the this contribution certificate corresponds to',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contribution_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributioncertificate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
