# Generated by Django 3.2.10 on 2022-01-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220104_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributioncertificate',
            name='is_signed_off',
            field=models.BooleanField(default=False, help_text='True if the certificate is signed'),
        ),
    ]
