# Generated by Django 3.2.10 on 2022-01-11 21:25

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220104_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributioncertificate',
            name='details',
            field=martor.models.MartorField(default='<EMPTY>', help_text='Markdown formatted details. This will be generated automatically by ContributionCertificate.gen_cert_detail_text, but can be set manually too.'),
            preserve_default=False,
        ),
    ]
