# Generated by Django 3.2.10 on 2022-01-12 23:09

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_contributioncertificate_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributioncertificate',
            name='details',
            field=martor.models.MartorField(help_text='Markdown formatted details. This will be generated automatically by ContributionCertificate.gen_cert_detail_text, but can be set manually too.\nIf this is modified, the certificate pdfs will need to be regenerated.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date joined'),
        ),
    ]
