# Generated by Django 4.0.7 on 2022-08-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220113_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.memberrecord'),
        ),
    ]
