# Generated by Django 3.2.10 on 2022-01-01 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0001_squashed_0021_alter_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the question was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='review_date',
            field=models.DateField(blank=True, help_text='Date the question was reviewed', null=True),
        ),
    ]
