# Generated by Django 3.1.6 on 2021-04-04 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcq_bank', '0002_auto_20210404_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Session Started')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Session Ended')),
                ('answers', models.ManyToManyField(blank=True, null=True, to='mcq_bank.Question')),
                ('questions', models.ManyToManyField(related_name='quiz_sessions', to='mcq_bank.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'permissions': (('view_sittings', 'Can see completed exams.'),),
            },
        ),
    ]
