# Generated by Django 3.2.4 on 2021-06-14 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
