# Generated by Django 3.2.4 on 2021-06-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0003_auto_20210614_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
