# Generated by Django 3.1.6 on 2021-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0004_auto_20210404_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_sessions', to='mcq_bank.Question'),
        ),
    ]
