# Generated by Django 3.1.3 on 2020-12-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0004_auto_20201204_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='explanation_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
