# Generated by Django 3.1.6 on 2021-04-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0005_auto_20210404_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='quiz_sessions', to='mcq_bank.Answer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='mcq_bank.question'),
        ),
    ]
