# Generated by Django 3.1.3 on 2020-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0005_auto_20201204_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
