# Generated by Django 3.2.4 on 2021-06-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0007_auto_20210628_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Enter the question text that you want displayed', max_length=1000, unique=True, verbose_name='Question text'),
        ),
    ]
