# Generated by Django 3.2.4 on 2021-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0007_auto_20210606_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='history',
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
