# Generated by Django 3.1.3 on 2020-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0007_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=None, choices=[('UNCATEGORISED', 'Uncategorised'), ('CARDIOLOGY', 'Cardiology'), ('NEUROLOGY', 'Neurology'), ('PAEDIATRICS', 'Paediatrics')], default='UNCATEGORISED', max_length=128, null=True),
        ),
    ]
