# Generated by Django 3.2.4 on 2021-06-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0008_auto_20210606_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sitting',
        ),
    ]
