# Generated by Django 3.2.4 on 2021-07-09 09:57

import django.db.models.deletion
from django.db import migrations, models

from medusa_website.mcq_bank.models.category import Category

none_category, _created = Category.objects.get_or_create(name="None")


class Migration(migrations.Migration):
    dependencies = [
        ('mcq_bank', '0009_alter_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=none_category.id, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='questions', to='mcq_bank.category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
