# Generated by Django 3.2.4 on 2021-07-12 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcq_bank', '0010_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flagged_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='If True, has been flagged by a user'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='If True, has been reviewed by a staff or admin'),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
