# Generated by Django 3.2.4 on 2021-07-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0012_auto_20210712_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, help_text='Extra explanation for this answer', null=True),
        ),
    ]
