# Generated by Django 3.2.4 on 2021-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0013_alter_answer_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(help_text='Enter the answer text that you want displayed', verbose_name='Text'),
        ),
    ]
