# Generated by Django 3.2.4 on 2021-07-12 13:13

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0014_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=martor.models.MartorField(help_text='Explanation to be shown after the question has been answered', verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Enter the question text that you want displayed', unique=True, verbose_name='Question text'),
        ),
    ]
