# Generated by Django 3.2.4 on 2021-07-13 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0015_auto_20210712_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mcq_bank.question', verbose_name='Question'),
        ),
    ]
