# Generated by Django 3.2.4 on 2021-08-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0018_auto_20210830_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, help_text='Upload an image to be shown with the answers', null=True, upload_to='', verbose_name='Answer Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Upload an image to be shown in the question prompt', null=True, upload_to='', verbose_name='Question Image'),
        ),
    ]
