# Generated by Django 3.2.4 on 2021-09-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0019_auto_20210830_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flagged_message',
            field=models.TextField(blank=True, help_text='Explanation for why the question was flagged.', null=True),
        ),
    ]
