# Generated by Django 3.2.4 on 2021-09-26 11:19

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_bank', '0020_question_flagged_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=martor.models.MartorField(blank=True, help_text='Explanation to be shown after the question has been answered', null=True, verbose_name='Explanation'),
        ),
    ]
