# Generated by Django 3.2.10 on 2022-01-01 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0001_squashed_0006_alter_committeemember_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='profile_pic',
        ),
    ]
