# Generated by Django 3.2.4 on 2021-07-19 11:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcommitee',
            name='org_chart_fill_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Should be a CSS compatible hex colour', max_length=18),
        ),
    ]
