# Generated by Django 3.2.10 on 2022-01-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0002_remove_committeemember_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='name',
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='email',
            field=models.EmailField(help_text='Must not be the personal email of the position holder', max_length=254),
        ),
    ]
