# Generated by Django 3.2.4 on 2021-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0002_alter_subcommitee_org_chart_fill_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commiteemember',
            name='position',
            field=models.CharField(help_text='Name of the position', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='subcommitee',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
