# Generated by Django 3.2.10 on 2022-01-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0003_auto_20220101_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommitteeMember',
            new_name='CommitteeRole',
        ),
    ]
