# Generated by Django 3.2.4 on 2021-07-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0003_auto_20210719_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the current holder of the position', max_length=128)),
                ('position', models.CharField(help_text='Name of the position', max_length=128, unique=True)),
                ('email', models.EmailField(help_text='Must be a medusa.org.au email, not the personal email of the position holder', max_length=254)),
                ('profile_pic', models.ImageField(help_text='Profile pic of the current committee member', upload_to='org_chart/images')),
            ],
        ),
        migrations.RenameModel(
            old_name='SubCommitee',
            new_name='SubCommittee',
        ),
        migrations.DeleteModel(
            name='CommiteeMember',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='sub_committee',
            field=models.ForeignKey(help_text='Subcommittee the position belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='org_chart.subcommittee'),
        ),
    ]
