# Generated by Django 3.2.4 on 2021-07-20 00:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0004_auto_20210719_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcommittee',
            name='explanation_text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
