# Generated by Django 3.2.10 on 2022-01-01 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_chart', '0004_rename_committeemember_committeerole'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMemberRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year that the user held this position in the committee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='org_chart.committeerole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('role', 'user', 'year')},
            },
        ),
    ]
