# Generated by Django 3.2.4 on 2021-07-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0005_subcommittee_explanation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Profile pic of the current committee member', null=True, upload_to='org_chart/images'),
        ),
    ]
