# Generated by Django 3.2.9 on 2021-12-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0006_alter_committeemember_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommitteeMember',
            new_name='CommitteePosition',
        ),
    ]
