# Generated by Django 3.2.10 on 2022-01-03 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_chart', '0007_alter_committeerole_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeememberrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_member_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
