# Generated by Django 3.2.10 on 2022-01-03 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_chart', '0008_alter_committeememberrecord_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommitteeMemberRecord',
            new_name='CommitteeRoleRecord',
        ),
    ]
