name: Deploy
on:
  [ push,  pull_request ]
jobs:
  deploy_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: source ~/medusa_website/post_commit_nostatic.sh
          host: ${{ secrets.SSH_HOST }}
          username: medusa_it
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
        env:
          CI: true
