name: Deploy
on:
  [ push,  pull_request ]

jobs:
  deploy_ssh:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Deploy via SSH script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: source ~/medusa_website/post_commit_nostatic.sh
          host: ${{ secrets.SSH_HOST }}
          username: medusa_it
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
        env:
          CI: true
